const experis = [
  {
    'id': '6004803',
    'company': 'Experis IT Manpower Group',
    'ratings_overall': 3.1,
    'details_size': 'Unknown',
    'details_type': 'Company - Public',
    'country_code': 'US',
    'company_type': 'Company - Public',
    'details_headquarters': 'Calcutta, India',
    'details_revenue': 'Unknown / Non-Applicable',
    'details_website': 'www.experisindia.com',
    'ratings_career_opportunities': 2.8,
    'ratings_ceo_approval': 0.82,
    'ratings_ceo_approval_count': 6,
    'ratings_compensation_benefits': 2.7,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '3.2',
    'diversity_inclusion_count': '61',
    'ratings_senior_management': 2.6,
    'ratings_work_life_balance': 3.3,
    'ratings_business_outlook': 0.39,
    'ratings_recommend_to_friend': 0.42,
    'salaries_count': 129,
    'career_opportunities_distribution': {
      'one_star': 15,
      'two_star': 10,
      'three_star': 17,
      'four_star': 14,
      'five_star': 9,
    },
    'interview_difficulty': 'EASY',
    'interviews_count': 7,
    'benefits_count': 7,
    'jobs_count': 0,
    'reviews_count': 90,
    'interviews_experience': [
      {
        'name': 'POSITIVE',
        'value': '86%',
      },
      {
        'name': 'NEUTRAL',
        'value': '14%',
      },
    ],
    'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-IT-Manpower-Group-EI_IE6004803.11,36.htm',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:12:33.510Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-IT-Manpower-Group-EI_IE6004803.11,36.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=experis',
      'max_search_results': 5,
    },
  },
  {
    'id': '8312472',
    'company': 'Experis',
    'ratings_overall': 3.6,
    'details_size': '51 to 200 Employees',
    'details_type': 'Company - Private',
    'country_code': 'US',
    'company_type': 'Company - Private',
    'details_headquarters': 'Buenos Aires, Argentina',
    'details_revenue': 'Unknown / Non-Applicable',
    'details_website': 'experis.manpowergroup.com.ar',
    'ratings_career_opportunities': 3.2,
    'ratings_ceo_approval': 0,
    'ratings_ceo_approval_count': 0,
    'ratings_compensation_benefits': 3,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '3.8',
    'diversity_inclusion_count': '34',
    'ratings_senior_management': 3.1,
    'ratings_work_life_balance': 3.7,
    'ratings_business_outlook': 0.47,
    'ratings_recommend_to_friend': 0.68,
    'salaries_count': 193,
    'career_opportunities_distribution': {
      'one_star': 5,
      'two_star': 7,
      'three_star': 10,
      'four_star': 11,
      'five_star': 3,
    },
    'interview_difficulty': 'VERY_EASY',
    'interviews_count': 8,
    'benefits_count': 12,
    'jobs_count': 0,
    'reviews_count': 67,
    'interviews_experience': [
      {
        'name': 'POSITIVE',
        'value': '50%',
      },
      {
        'name': 'NEGATIVE',
        'value': '38%',
      },
      {
        'name': 'NEUTRAL',
        'value': '13%',
      },
    ],
    'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-EI_IE8312472.11,18.htm',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:13:01.872Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-EI_IE8312472.11,18.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=experis',
      'max_search_results': 5,
    },
  },
  {
    'id': '608019',
    'company': 'Experis',
    'ratings_overall': 3.5,
    'details_size': '5001 to 10000 Employees',
    'details_founded': 1953,
    'details_type': 'Subsidiary or Business Segment',
    'country_code': 'US',
    'company_type': 'Subsidiary or Business Segment',
    'details_headquarters': 'Milwaukee, WI',
    'details_industry': 'HR Consulting',
    'details_revenue': '$25 to $100 million (USD)',
    'details_website': 'www.experis.com',
    'ratings_career_opportunities': 3.2,
    'ratings_ceo_approval': 0.69,
    'ratings_ceo_approval_count': 781,
    'ratings_compensation_benefits': 3.1,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '3.7',
    'diversity_inclusion_count': '1003',
    'ratings_senior_management': 3.3,
    'ratings_work_life_balance': 3.6,
    'ratings_business_outlook': 0.55,
    'ratings_recommend_to_friend': 0.63,
    'ratings_rated_ceo': 'Jonas Prising ',
    'competitors': 'Robert Half,Adecco,Robert Walters',
    'salaries_count': 5820,
    'career_opportunities_distribution': {
      'one_star': 432,
      'two_star': 273,
      'three_star': 435,
      'four_star': 413,
      'five_star': 440,
    },
    'interview_difficulty': 'EASY',
    'interviews_count': 384,
    'benefits_count': 766,
    'jobs_count': 754,
    'photos_count': '31',
    'reviews_count': 3287,
    'interviews_experience': [
      {
        'name': 'POSITIVE',
        'value': '55%',
      },
      {
        'name': 'NEGATIVE',
        'value': '25%',
      },
      {
        'name': 'NEUTRAL',
        'value': '20%',
      },
    ],
    'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-EI_IE608019.11,18.htm',
    'industry': 'HR Consulting',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:14:26.991Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-EI_IE608019.11,18.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=experis',
      'max_search_results': 5,
    },
  },
  {
    'id': '519101',
    'company': 'Experis India',
    'ratings_overall': 3.1,
    'details_size': '501 to 1000 Employees',
    'details_type': 'Company - Private',
    'country_code': 'US',
    'company_type': 'Company - Private',
    'details_headquarters': 'Calcutta, India',
    'details_industry': 'HR Consulting',
    'details_revenue': 'Unknown / Non-Applicable',
    'details_website': 'www.experisindia.com',
    'ratings_career_opportunities': 2.9,
    'ratings_ceo_approval': 0.51,
    'ratings_ceo_approval_count': 46,
    'ratings_compensation_benefits': 2.8,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '3.1',
    'diversity_inclusion_count': '141',
    'ratings_senior_management': 2.6,
    'ratings_work_life_balance': 3,
    'ratings_business_outlook': 0.4,
    'ratings_recommend_to_friend': 0.48,
    'ratings_rated_ceo': 'Sanju Ballurkar',
    'salaries_count': 469,
    'career_opportunities_distribution': {
      'one_star': 85,
      'two_star': 46,
      'three_star': 142,
      'four_star': 260,
      'five_star': 155,
    },
    'interview_difficulty': 'DIFFICULT',
    'interviews_count': 126,
    'benefits_count': 172,
    'jobs_count': 61309,
    'photos_count': '15',
    'reviews_count': 1001,
    'interviews_experience': [
      {
        'name': 'POSITIVE',
        'value': '72%',
      },
      {
        'name': 'NEGATIVE',
        'value': '9%',
      },
      {
        'name': 'NEUTRAL',
        'value': '20%',
      },
    ],
    'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-India-EI_IE519101.11,24.htm',
    'industry': 'HR Consulting',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:17:45.697Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-India-EI_IE519101.11,24.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=experis',
      'max_search_results': 5,
    },
  },
  {
    'id': '6535156',
    'company': 'Experis (France)',
    'ratings_overall': 2.9,
    'details_size': '1 to 50 Employees',
    'details_type': 'Franchise',
    'country_code': 'US',
    'company_type': 'Franchise',
    'details_headquarters': 'Paris, France',
    'details_revenue': 'Unknown / Non-Applicable',
    'details_website': 'www.expersi.com',
    'ratings_career_opportunities': 2.5,
    'ratings_ceo_approval': 0,
    'ratings_ceo_approval_count': 0,
    'ratings_compensation_benefits': 1.9,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '2.4',
    'diversity_inclusion_count': '16',
    'ratings_senior_management': 2.1,
    'ratings_work_life_balance': 2.3,
    'ratings_business_outlook': 0.18,
    'ratings_recommend_to_friend': 0.35,
    'salaries_count': 35,
    'career_opportunities_distribution': {
      'one_star': 4,
      'two_star': 4,
      'three_star': 4,
      'four_star': 3,
      'five_star': 1,
    },
    'interviews_count': 0,
    'benefits_count': 2,
    'jobs_count': 0,
    'reviews_count': 21,
    'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-France-EI_IE6535156.11,25.htm',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:20:37.838Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Experis-France-EI_IE6535156.11,25.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=experis',
      'max_search_results': 5,
    },
  },
];

const abdridge = [
  {
    'id': '3339164',
    'company': 'Abridge Marketing Solutions',
    'ratings_overall': 5,
    'details_size': '1 to 50 Employees',
    'details_type': 'Company - Private',
    'country_code': 'US',
    'company_type': 'Company - Private',
    'details_headquarters': 'Indore, India',
    'details_revenue': 'Unknown / Non-Applicable',
    'details_website': 'www.abridgemspl.com',
    'ratings_career_opportunities': 5,
    'ratings_ceo_approval': 0,
    'ratings_ceo_approval_count': 0,
    'ratings_compensation_benefits': 5,
    'ratings_cutlure_values': 0,
    'ratings_senior_management': 5,
    'ratings_work_life_balance': 5,
    'ratings_business_outlook': 1,
    'ratings_recommend_to_friend': 1,
    'salaries_count': 1,
    'career_opportunities_distribution': {
      'one_star': 0,
      'two_star': 0,
      'three_star': 0,
      'four_star': 0,
      'five_star': 1,
    },
    'interviews_count': 0,
    'benefits_count': 0,
    'jobs_count': 0,
    'reviews_count': 1,
    'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-Marketing-Solutions-EI_IE3339164.11,38.htm',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:33:44.266Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-Marketing-Solutions-EI_IE3339164.11,38.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=abridge',
      'max_search_results': 5,
    },
  },
  {
    'id': '3146134',
    'company': 'Abridge',
    'ratings_overall': 4.6,
    'details_size': '51 to 200 Employees',
    'details_founded': 2018,
    'details_type': 'Company - Private',
    'country_code': 'US',
    'company_type': 'Company - Private',
    'details_headquarters': 'Pittsburgh, PA',
    'details_industry': 'Health Care Services & Hospitals',
    'details_revenue': 'Unknown / Non-Applicable',
    'details_website': 'https://www.abridge.com',
    'ratings_career_opportunities': 4.6,
    'ratings_ceo_approval': 0.91,
    'ratings_ceo_approval_count': 20,
    'ratings_compensation_benefits': 4.6,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '4.5',
    'diversity_inclusion_count': '21',
    'ratings_senior_management': 4.6,
    'ratings_work_life_balance': 4.5,
    'ratings_business_outlook': 0.9,
    'ratings_recommend_to_friend': 0.91,
    'ratings_rated_ceo': 'Shivdev Rao',
    'salaries_count': 25,
    'career_opportunities_distribution': {
      'one_star': 1,
      'two_star': 1,
      'three_star': 0,
      'four_star': 2,
      'five_star': 17,
    },
    'interview_difficulty': 'VERY_DIFFICULT',
    'interviews_count': 16,
    'benefits_count': 4,
    'jobs_count': 99,
    'photos_count': '6',
    'reviews_count': 26,
    'interviews_experience': [
      {
        'name': 'POSITIVE',
        'value': '38%',
      },
      {
        'name': 'NEGATIVE',
        'value': '44%',
      },
      {
        'name': 'NEUTRAL',
        'value': '19%',
      },
    ],
    'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-EI_IE3146134.11,18.htm',
    'industry': 'Health Care Services & Hospitals',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:33:54.598Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-EI_IE3146134.11,18.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=abridge',
      'max_search_results': 5,
    },
  },
  {
    'id': '5171076',
    'company': 'Abridge',
    'ratings_overall': 4,
    'details_size': '1 to 50 Employees',
    'details_type': 'Company - Private',
    'country_code': 'US',
    'company_type': 'Company - Private',
    'details_headquarters': 'Tokyo, Japan',
    'details_revenue': 'Unknown / Non-Applicable',
    'details_website': 'www.abridge-co.jp',
    'ratings_career_opportunities': 5,
    'ratings_ceo_approval': 0,
    'ratings_ceo_approval_count': 0,
    'ratings_compensation_benefits': 5,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '5',
    'diversity_inclusion_count': '1',
    'ratings_senior_management': 5,
    'ratings_work_life_balance': 4,
    'ratings_business_outlook': 0.67,
    'ratings_recommend_to_friend': 0.67,
    'salaries_count': 1,
    'career_opportunities_distribution': {
      'one_star': 0,
      'two_star': 0,
      'three_star': 0,
      'four_star': 0,
      'five_star': 1,
    },
    'interviews_count': 0,
    'benefits_count': 0,
    'jobs_count': 0,
    'reviews_count': 2,
    'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-EI_IE5171076.11,18.htm',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:34:00.013Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-EI_IE5171076.11,18.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=abridge',
      'max_search_results': 5,
    },
  },
  {
    'id': '423819',
    'company': 'Abridge Info Systems',
    'ratings_overall': 4,
    'details_size': '1 to 50 Employees',
    'details_founded': 2006,
    'details_type': 'Company - Private',
    'country_code': 'US',
    'company_type': 'Company - Private',
    'details_headquarters': 'Chelmsford, MA',
    'details_industry': 'Information Technology Support Services',
    'details_revenue': '$1 to $5 million (USD)',
    'details_website': 'www.abridgeinfo.com',
    'ratings_career_opportunities': 3.3,
    'ratings_ceo_approval': 1,
    'ratings_ceo_approval_count': 3,
    'ratings_compensation_benefits': 3.6,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '4',
    'diversity_inclusion_count': '3',
    'ratings_senior_management': 4,
    'ratings_work_life_balance': 3.6,
    'ratings_business_outlook': 0.64,
    'ratings_recommend_to_friend': 0.64,
    'ratings_rated_ceo': 'Abhijit Deshmukh',
    'salaries_count': 212,
    'career_opportunities_distribution': {
      'one_star': 0,
      'two_star': 1,
      'three_star': 0,
      'four_star': 2,
      'five_star': 0,
    },
    'interviews_count': 0,
    'benefits_count': 0,
    'jobs_count': 0,
    'photos_count': '2',
    'reviews_count': 3,
    'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-Info-Systems-EI_IE423819.11,31.htm',
    'industry': 'Information Technology Support Services',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:34:01.211Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-Info-Systems-EI_IE423819.11,31.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=abridge',
      'max_search_results': 5,
    },
  },
  {
    'id': '6346014',
    'company': 'Abridge IT Firm',
    'ratings_overall': 4,
    'details_size': '1 to 50 Employees',
    'details_type': 'Company - Public',
    'country_code': 'US',
    'company_type': 'Company - Public',
    'details_headquarters': 'Dhaka, Bangladesh',
    'details_revenue': 'Unknown / Non-Applicable',
    'details_website': 'www.abridgeitfirm.com',
    'ratings_career_opportunities': 3.4,
    'ratings_ceo_approval': 0,
    'ratings_ceo_approval_count': 0,
    'ratings_compensation_benefits': 4,
    'ratings_cutlure_values': 0,
    'diversity_inclusion_score': '3.1',
    'diversity_inclusion_count': '3',
    'ratings_senior_management': 3.8,
    'ratings_work_life_balance': 3.8,
    'ratings_business_outlook': 0.69,
    'ratings_recommend_to_friend': 0.69,
    'salaries_count': 5,
    'career_opportunities_distribution': {
      'one_star': 1,
      'two_star': 0,
      'three_star': 0,
      'four_star': 1,
      'five_star': 1,
    },
    'interviews_count': 0,
    'benefits_count': 0,
    'jobs_count': 0,
    'reviews_count': 3,
    'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-IT-Firm-EI_IE6346014.11,26.htm',
    'additional_information': null,
    'stock_symbol': null,
    'timestamp': '2024-11-14T00:34:04.994Z',
    'input': {
      'url': 'https://www.glassdoor.com/Overview/Working-at-Abridge-IT-Firm-EI_IE6346014.11,26.htm',
      'days': 7,
    },
    'discovery_input': {
      'search_url': 'https://www.glassdoor.com/Search/results.htm?keyword=abridge',
      'max_search_results': 5,
    },
  },
];
