import textWithEllipsis from './textWithEllipsis';
import useNotifications from './useNotifications';
import { affindaResumeTransformer } from './affindaUtils';
import { coreSignalResumeTransformer } from './coreSignalUtils';
import {
  numberWithCommas,
  convertMilesToMeters,
  convertMetersToMiles,
  getGeoLocationFromAddress,
  selectFile,
  toTitleCase,
  transformMonthToString,
  transformDateToText,
  deepEqualCheck,
  onShare,
  filterArrayOfObjectsByKey,
  getFirstNameAndInitialFromFullName,
  isOdd,
  getMatchesContainerHeight,
  reorderObjectArrayByDate,
  getLargestNumberFromArray,
  getSmallestNumberFromArray,
  transformYearToString,
  isPastJobComplete,
  isEducationHistoryItemComplete,
  getRelevantSkillsFromJobHistory,
  removeDuplicateStringsFromArray,
  getMatchesFromEmployersJobs,
  getPropByString,
  prefetchImages,
} from './globalUtils';

export {
  textWithEllipsis,
  numberWithCommas,
  convertMilesToMeters,
  convertMetersToMiles,
  useNotifications,
  getGeoLocationFromAddress,
  selectFile,
  affindaResumeTransformer,
  toTitleCase,
  transformMonthToString,
  transformDateToText,
  deepEqualCheck,
  onShare,
  filterArrayOfObjectsByKey,
  getFirstNameAndInitialFromFullName,
  isOdd,
  getMatchesContainerHeight,
  reorderObjectArrayByDate,
  getLargestNumberFromArray,
  getSmallestNumberFromArray,
  transformYearToString,
  isPastJobComplete,
  isEducationHistoryItemComplete,
  getRelevantSkillsFromJobHistory,
  removeDuplicateStringsFromArray,
  getMatchesFromEmployersJobs,
  coreSignalResumeTransformer,
  getPropByString,
  prefetchImages,
};
