service: pare
app: pare
org: jobfindingapp778

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs18.x
  timeout: 20
  httpApi:
    cors: true
  websocketsApiName: job-app-websockets-api
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  environment:
    # keeperImageUploadBucket: ${self:custom.keeperImageUploadBucket}
    region: 'us-east-1'
  iamRoleStatements:
    # Allow sending emails with SES
    - Effect: 'Allow'
      Action:
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
        - 'ses:SendTemplatedEmail'
      Resource: '*'

    # Allow interaction with SQS queues
    - Effect: 'Allow'
      Action:
        - 'sqs:SendMessage'
        - 'sqs:ReceiveMessage'
        - 'sqs:DeleteMessage'
        - 'sqs:GetQueueUrl'
      Resource: 'arn:aws:sqs:us-east-1:*:*'

    # Allow S3 operations (limit to required actions if possible)
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
        - 's3:GetObject'
        - 's3:DeleteObject'
        - 's3:ListBucket'
      Resource: 'arn:aws:s3:::*' # Ideally specify the exact bucket ARN(s)

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-webpack

custom:
  webpack:
    webpackConfig: './webpack.config.ts' # Specify the Webpack config file
    includeModules: true # Automatically include required `node_modules`
    packager: npm # Set package manager (npm or yarn)
    packagerOptions:
      scripts:
        - 'npm rebuild' # Ensure any native dependencies are properly rebuilt

  prune:
    automatic: true
    number: 3

# resources:
#   Resources:
#     KeeperImageUploadBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${self:custom.keeperImageUploadBucket}
#         AccessControl: PublicRead

resources:
  Resources:
    # DLQs
    JobsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: JobsDLQ

    GeoLocationDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GeoLocationDLQ

    SourceWebsiteCompaniesDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SourceWebsiteCompaniesDLQ

    GlassdoorCompaniesDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GlassdoorCompaniesDLQ

    CrunchbaseCompaniesDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CrunchbaseCompaniesDLQ

    GlassdoorReviewsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GlassdoorReviewsDLQ

    # Main Queues with DLQs
    JobsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: JobsQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt JobsDLQ.Arn
          maxReceiveCount: 3

    GeoLocationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GeoLocationQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt GeoLocationDLQ.Arn
          maxReceiveCount: 3

    SourceWebsiteCompaniesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SourceWebsiteCompaniesQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt SourceWebsiteCompaniesDLQ.Arn
          maxReceiveCount: 3

    GlassdoorCompaniesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GlassdoorCompaniesQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt GlassdoorCompaniesDLQ.Arn
          maxReceiveCount: 3

    CrunchbaseCompaniesQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: CrunchbaseCompaniesQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt CrunchbaseCompaniesDLQ.Arn
          maxReceiveCount: 3

    GlassdoorReviewsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: GlassdoorReviewsQueue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt GlassdoorReviewsDLQ.Arn
          maxReceiveCount: 3

functions:
  triggerBrightDataQueues:
    handler: functions/brightData/triggerBrightDataQueues.handler
    events:
      - http:
          path: triggerBrightDataQueues
          method: post
          cors: true

  processJobsQueue:
    handler: functions/brightData/processJobsQueue.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JobsQueue
              - Arn
          batchSize: 10

  processGeoLocationQueue:
    handler: functions/brightData/processGeoLocationQueue.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - GeoLocationQueue
              - Arn
          batchSize: 10

  processSourceWebsiteCompaniesQueue:
    handler: functions/brightData/processSourceWebsiteCompaniesQueue.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SourceWebsiteCompaniesQueue
              - Arn
          batchSize: 10

  processGlassdoorCompaniesQueue:
    handler: functions/brightData/processGlassdoorCompaniesQueue.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - GlassdoorCompaniesQueue
              - Arn
          batchSize: 10

  processCrunchbaseCompaniesQueue:
    handler: functions/brightData/processCrunchbaseCompaniesQueue.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - processCrunchbaseCompaniesQueue
              - Arn
          batchSize: 10

  processGlassdoorReviewsQueue:
    handler: functions/brightData/processGlassdoorReviewsQueue.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - GlassdoorReviewsQueue
              - Arn
          batchSize: 10

  imageUpload:
    handler: functions/misc/imageUpload.handler
    events:
      - http:
          path: imageUpload
          method: post
          cors: true

  getGoogleMapsLocations:
    handler: functions/misc/getGoogleMapsLocations.handler
    events:
      - http:
          path: getGoogleMapsLocations
          method: post
          cors: true

  sendPubnubNotification:
    handler: functions/misc/sendPubnubNotification.handler
    events:
      - http:
          path: sendPubnubNotification
          method: post
          cors: true

  preSignUp:
    handler: functions/users/preSignUp.handler
    events:
      - http:
          path: preSignUp
          method: post
          cors: true

  addCognitoUserToMongoDb:
    handler: functions/users/addCognitoUserToMongoDb.handler
    events:
      - http:
          path: addCognitoUserToMongoDb
          method: post
          cors: true

  recordSwipe:
    handler: functions/users/recordSwipe.handler
    events:
      - http:
          path: recordSwipe
          method: post
          cors: true

  updateExpoPushToken:
    handler: functions/users/updateExpoPushToken.handler
    events:
      - http:
          path: updateExpoPushToken
          method: post
          cors: true

  addEmployer:
    handler: functions/users/addEmployer.handler
    events:
      - http:
          path: addEmployer
          method: post
          cors: true

  getEmployee:
    handler: functions/users/getEmployee.handler
    events:
      - http:
          path: getEmployee
          method: post
          cors: true

  setEmployeeFieldOnAllDocuments:
    handler: functions/users/setEmployeeFieldOnAllDocuments.handler
    events:
      - http:
          path: setEmployeeFieldOnAllDocuments
          method: post
          cors: true

  getEmployeesForSwiping:
    handler: functions/users/getEmployeesForSwiping.handler
    events:
      - http:
          path: getEmployeesForSwiping
          method: post
          cors: true

  getEmployer:
    handler: functions/users/getEmployer.handler
    events:
      - http:
          path: getEmployer
          method: post
          cors: true

  getEmployerData:
    handler: functions/users/getEmployerData.handler
    events:
      - http:
          path: getEmployerData
          method: post
          cors: true

  getEmployeeData:
    handler: functions/users/getEmployeeData.handler
    timeout: 30
    events:
      - http:
          path: getEmployeeData
          method: post
          cors: true

  addMatch:
    handler: functions/users/addMatch.handler
    events:
      - http:
          path: addMatch
          method: post
          cors: true

  updateMatchForBothOwners:
    handler: functions/users/updateMatchForBothOwners.handler
    events:
      - http:
          path: updateMatchForBothOwners
          method: post
          cors: true

  updateOwnMatch:
    handler: functions/users/updateOwnMatch.handler
    events:
      - http:
          path: updateOwnMatch
          method: post
          cors: true

  deleteMatch:
    handler: functions/users/deleteMatch.handler
    events:
      - http:
          path: deleteMatch
          method: post
          cors: true

  updateUserSettings:
    handler: functions/users/updateUserSettings.handler
    events:
      - http:
          path: updateUserSettings
          method: post
          cors: true

  updateMatchNotification:
    handler: functions/users/updateMatchNotification.handler
    events:
      - http:
          path: updateMatchNotification
          method: post
          cors: true

  updateUserData:
    handler: functions/users/updateUserData.handler
    events:
      - http:
          path: updateUserData
          method: post
          cors: true

  getUsersByArrayOfIds:
    handler: functions/users/getUsersByArrayOfIds.handler
    events:
      - http:
          path: getUsersByArrayOfIds
          method: post
          cors: true

  updateEmployeePreferences:
    handler: functions/users/updateEmployeePreferences.handler
    events:
      - http:
          path: updateEmployeePreferences
          method: post
          cors: true

  # updateJobPreferences:
  #   handler: functions/jobs/updateJobPreferences.handler
  #   events:
  #     - http:
  #         path: updateJobPreferences
  #         method: post
  #         cors: true

  # addJob:
  #   handler: functions/jobs/addJob.handler
  #   events:
  #     - http:
  #         path: addJob
  #         method: post
  #         cors: true

  # updateJobData:
  #   handler: functions/jobs/updateJobData.handler
  #   events:
  #     - http:
  #         path: updateJobData
  #         method: post
  #         cors: true

  # deleteJob:
  #   handler: functions/jobs/deleteJob.handler
  #   events:
  #     - http:
  #         path: deleteJob
  #         method: post
  #         cors: true

  getJobsForSwiping:
    handler: functions/jobs/getJobsForSwiping.handler
    events:
      - http:
          path: getJobsForSwiping
          method: post
          cors: true

  # onSelectJob:
  #   handler: functions/jobs/onSelectJob.handler
  #   events:
  #     - http:
  #         path: onSelectJob
  #         method: post
  #         cors: true

  # getEmployersJobs:
  #   handler: functions/jobs/getEmployersJobs.handler
  #   events:
  #     - http:
  #         path: getEmployersJobs
  #         method: post
  #         cors: true
# updateJobSettings:
#   handler: functions/jobs/updateJobSettings.handler
#   events:
#     - http:
#         path: updateJobSettings
#         method: post
#         cors: true

# setJobFieldOnAllDocuments:
#   handler: functions/jobs/setJobFieldOnAllDocuments.handler
#   events:
#     - http:
#         path: setJobFieldOnAllDocuments
#         method: post
#         cors: true

# getJobById:
#   handler: functions/jobs/getJobById.handler
#   events:
#     - http:
#         path: getJobById
#         method: post
#         cors: true

# searchCompanyName:
#   handler: functions/jobs/searchCompanyName.handler
#   events:
#     - http:
#         path: searchCompanyName
#         method: post
#         cors: true
