import textWithEllipsis from './textWithEllipsis';

import { affindaResumeTransformer } from './affindaUtils';
import { coreSignalResumeTransformer } from './coreSignalUtils';
import {
  numberWithCommas,
  convertMilesToMeters,
  convertMetersToMiles,
  getGeoLocationFromAddress,
  toTitleCase,
  transformMonthToString,
  transformDateToText,
  deepEqualCheck,
  onShare,
  filterArrayOfObjectsByKey,
  getFirstNameAndInitialFromFullName,
  isOdd,
  getMatchesContainerHeight,
  reorderObjectArrayByDate,
  closeModalWithAlert,
  getLargestNumberFromArray,
  getSmallestNumberFromArray,
  transformYearToString,
  isPastJobComplete,
  isEducationHistoryItemComplete,
  removeDuplicateStringsFromArray,
  getMatchesFromEmployersJobs,
  convertBase64ToBlob,
  convertBase64,
  getPropByString,
} from './globalUtils';

export {
  textWithEllipsis,
  numberWithCommas,
  convertMilesToMeters,
  convertMetersToMiles,
  getGeoLocationFromAddress,
  affindaResumeTransformer,
  toTitleCase,
  transformMonthToString,
  transformDateToText,
  deepEqualCheck,
  onShare,
  filterArrayOfObjectsByKey,
  getFirstNameAndInitialFromFullName,
  isOdd,
  getMatchesContainerHeight,
  reorderObjectArrayByDate,
  closeModalWithAlert,
  getLargestNumberFromArray,
  getSmallestNumberFromArray,
  transformYearToString,
  isPastJobComplete,
  isEducationHistoryItemComplete,
  removeDuplicateStringsFromArray,
  getMatchesFromEmployersJobs,
  convertBase64ToBlob,
  convertBase64,
  coreSignalResumeTransformer,
  getPropByString,
};
